stages:
    - test
    - sonarqube-check
    - build
    - release
    - deploy

variables:
    IMAGE_NAME_COMMIT: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:build
    IMAGE_NAME_LATEST: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest
    CONTAINER_NAME: javapro_teams27_backend

test:
    stage: test
    tags:
        - social-server-2
    script:
        - mvn clean test
    only:
        - dev

build:
    stage: build
    tags:
        - social-server-2
    script:
        - docker build -t $IMAGE_NAME_COMMIT ./
    only:
        - dev

release:
    stage: release
    tags:
        - social-server-2
    before_script:
        - docker stop $CONTAINER_NAME || exit_code=0
        - docker rm $CONTAINER_NAME || exit_code=0
        - docker rmi $IMAGE_NAME_LATEST || exit_code=0
    script:
        - docker tag $IMAGE_NAME_COMMIT $IMAGE_NAME_LATEST
    after_script:
        - docker rmi $IMAGE_NAME_COMMIT
    only:
        - dev

deploy:
    stage: deploy
    tags:
        - social-server-2
    script:
        - docker run -d -p 8086:8086 --name $CONTAINER_NAME $IMAGE_NAME_LATEST
    only:
        - dev
        
sonarqube-check:
    stage: sonarqube-check
    tags:
        - social-server-2
    image: maven:3.6.3-jdk-11
    variables:
        SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
        GIT_DEPTH: "0"  
    cache:
        key: "${CI_JOB_NAME}"
        paths:
        - .sonar/cache
    script: 
        - mvn verify sonar:sonar -Dsonar.projectKey=social_network2.0
    allow_failure: true
    only:
        - dev
