CREATE INDEX ON city (title);
CREATE INDEX ON post_comment (post_id, parent_id, is_deleted);
CREATE INDEX ON post_comment (post_id, is_deleted);
CREATE INDEX ON currency (name);
CREATE INDEX ON dialog (first_person_id, second_person_id);
CREATE INDEX ON friendship (src_person_id, dst_person_id);
CREATE INDEX ON post_like (post_id, type);
CREATE INDEX ON message (dialog_id, recipient_id, read_status);
CREATE INDEX ON message (recipient_id, read_status);
CREATE INDEX ON message (author_id);
CREATE INDEX ON notification (person_id);
CREATE INDEX ON person (email);
CREATE INDEX ON person (birth_date);
CREATE INDEX ON person (notifications_session_id);
CREATE INDEX ON person_settings (person_id);
CREATE INDEX ON post (author_id);
CREATE INDEX ON post (time, is_deleted);
CREATE INDEX ON post (is_deleted, time_delete);
CREATE INDEX ON tag (tag);
CREATE INDEX ON post2tag (post_id);