server:
    port: 8086

spring:
    profiles:
        active: prod
    mail:
        host: smtp.yandex.ru
        port: 465
        username: javaproteams27
        password: ddlmgyrcybsvjthu
        properties:
            mail:
                smtp:
                    auth: true
                    ssl:
                        enable: true

logging:
    level:
        root: info
    profiles:
        active: prod

yandexprofile:
    login: javaproteams27@yandex.ru
    token: y0_AgAAAABkHWYcAAhcJAAAAADNMMSQdTIhTbQjRfCCNvyw30mWw_U7WIY

logsupload:
    enabled: false
